@isTest
public class HighValueOpportunityEmailTest {
    // @isTest
    // static void testTrigger() {
    //     Opportunity opp = new Opportunity(Name = 'Big Deal', StageName = 'Prospecting', CloseDate = Date.today(), Amount = 150000, Email__c = 'test@example.com');

    //     Test.startTest();
    //     insert opp;
    //     Test.stopTest();

    //     Opportunity insertedOpp = [SELECT Id, Amount, Email__c FROM Opportunity WHERE Id = :opp.Id];
    //     System.assertEquals('test@example.com', insertedOpp.Email__c);
    // }
}